### ISSUE TITLE
Create more detailed instructions for deployment on render.com

### ISSUE THREAD

**Issue by mb0x88** [CryptoGrampy/HotShop#151]
trying to deploy on render.com and getting
`npm ERR! notsup Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

Would you be able to shed some light on how to deploy it?

**Comment by CryptoGrampy** [comment]
Looks like you found a bug :).  Render must have made an update recently and started allowing users to define the node version in their builder- this was causing issues because it was building with node 14.  Seems like things are working again (I added a file to specify node version), but the important settings you need for deploying on Render.com:

Repository: https://github.com/CryptoGrampy/HotShop
Branch: master
Build command: npm run build
Publish directory: dist

Let me know if you have any issues.

**Comment by mb0x88** [comment]
great it worked thanks
